/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useMemo, useRef } from "react"
import { useGLTF, MeshTransmissionMaterial, Edges } from "@react-three/drei"
import { useFrame, useThree } from "@react-three/fiber"
import { useControls } from "leva"

export function Model(props) {
  const { nodes, materials } = useGLTF("/assets/mxk-logo.glb")

  const { viewport } = useThree()
  const model = useRef()

  const geometry = useMemo(
    () => [
      nodes.M1.geometry,
      nodes.M2.geometry,
      nodes.M3.geometry,
      nodes.K1.geometry,
      nodes.K2.geometry,
      nodes.K3.geometry,
    ],
    []
  )

  useFrame((state, delta) => {
    model.current.rotation.y += 0.05 * delta
  })

  return (
    <group {...props} dispose={null} scale={viewport.width / 20} ref={model}>
      {geometry.map((geometry, index) => (
        <mesh
          key={index}
          geometry={geometry}
          material={materials.Material}
          position={[0.333, -0.734, 0.043]}
        >
          <Edges color="white" linewidth={2} />
        </mesh>
      ))}
    </group>
  )
}

useGLTF.preload("/mxk-logo.glb")
