import { Manrope } from "next/font/google"
import localFont from "next/font/local"
import "./globals.css"

const biggerFont = localFont({
  src: "../public/fonts/BiggerDisplay.woff2",
  display: "swap",
})

const manrope = Manrope({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={manrope.className}>{children}</body>
    </html>
  )
}
